### PR TITLE
Frontend v1

### PR DESCRIPTION
**Pull request by Saurabh-Chaurasia12**

### CODE REVIEW

**Comment by Saurabh-Chaurasia12** [comment]
@PranavS1604 Also helped in building up frontend --> mainly login and contact page

**Comment by metavinayak** [comment]
Frontend looks great!

For services don't use images/tiles, just make a simple table showing domain, status of website, tickets, etc
You can remove contact page.

add the frontend files in the `src/templates` folder and adjust the backend as per it. Use jinja templates in the html files to show the table data received from backend(`/services`).

Also the CSS and JS in html file needs to go in `src/static/style.css` and `src/static/style.js` to reduce redundancy.

To give credits to another person: use [coauthoring](https://medium.com/@geisterbar/how-to-add-co-author-s-to-a-commit-bf699cfc2d56)

**Comment by Saurabh-Chaurasia12** [comment]
Actually @PranavS1604 said that @piyush-panpaliya wanted style and js files inside html file.

**Comment by metavinayak** [comment]
It is not good to create commits for every file, instead do it based on feature/function.
It would be great if you can squash the commits to the necessary ones(eg: all deletes in single commit). Refer the internet/youtube. [git squashing](https://www.freecodecamp.org/news/git-squash-commits/)

After squashing, check git log and then push to this same branch. No need for new PR.
Will be a good git practise :)

@piyush-panpaliya @PranavS1604 help with backend integration and modular format.

**Comment by metavinayak** [comment]
Reminder

**Comment by metavinayak** [comment]
Pull from latest dev branch, handle merge conflicts then push

**Pull request merged**
