### PR TITLE
check status cron

### PR DESCRIPTION
**Pull request by piyush-json**
- added cron that check status of all services
- add downtime if found
- example env
- a scraping script that scraps all the conf file in **nginx-sites-enabled**

### CODE REVIEW

**Comment by piyush-json** [comment]
known issue
- not handling non iitmandi.co.in websites and iitmandi.co.in website

**Comment by piyush-json** [comment]
- fixed iitmandi.co.in
- updated requirements.txt

**Comment by metavinayak** [comment]
Uncomment `scrap()` and `cronCall()` in scrap.py

Display services in homepage in frontend.

Seems good overall, more work needed on frontend. Merging for now.

**Comment by piyush-json** [comment]
> Uncomment `scrap()` and `cronCall()` in scrap.py
> 
> Display services in homepage in frontend.
> 
> Seems good overall, more work needed on frontend. Merging for now.

uncommenting scrap is required but function in cron.py runs by scheduler in __init__.py

**Pull request merged**
